# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.price import Price
from swagger_server import util


class Product(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, current_price: Price=None):  # noqa: E501
        """Product - a model defined in Swagger

        :param id: The id of this Product.  # noqa: E501
        :type id: int
        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param current_price: The current_price of this Product.  # noqa: E501
        :type current_price: Price
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'current_price': Price
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'current_price': 'current_price'
        }

        self._id = id
        self._name = name
        self._current_price = current_price

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Product.


        :return: The id of this Product.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Product.


        :param id: The id of this Product.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Product.


        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.


        :param name: The name of this Product.
        :type name: str
        """

        self._name = name

    @property
    def current_price(self) -> Price:
        """Gets the current_price of this Product.


        :return: The current_price of this Product.
        :rtype: Price
        """
        return self._current_price

    @current_price.setter
    def current_price(self, current_price: Price):
        """Sets the current_price of this Product.


        :param current_price: The current_price of this Product.
        :type current_price: Price
        """

        self._current_price = current_price
